/oak_1_w:
  ros__parameters:
    camera:
      i_mx_id: ''
      i_nn_type: none
      i_enable_ir: false
      i_pipeline_type: RGB
      i_enable_imu: false
    left:
      i_resolution: 720p
      i_enable_lazy_publisher: false


/oak_1:
  ros__parameters:
    camera:
      i_mx_id: ''
      i_nn_type: none
      i_enable_ir: false
      i_pipeline_type: RGB
      i_enable_imu: false
    left: 
      i_resolution: 720p
      i_enable_lazy_publisher: false